// Pillole di tutti i giorni.
export const pillole = [
  "Siate il meglio di qualunque cosa siate. Cercate ardentemente di scoprire a cosa siete chiamati, poi mettetevi a farlo appassionatamente.",
  // Dai manifesti (1992-1998).
  "Se non miri a qualcosa, non colpirai mai nulla.",
  "Solo il meglio è abbastanza buono.",
  "La chiave del successo è avere due attività contemporaneamente: il proprio lavoro e il miglioramento del proprio lavoro.",
  "Il perdente ha sempre una scusa. Il vincente ha sempre un programma.",
  "Il perdente dice: «Questo non è il mio lavoro». Il vincente dice: «Lascia che lo faccia io per te».",
  "Il perdente dice che può essere possibile, ma che è troppo difficile. Il vincente dice che è difficile, ma che è possibile.",
  "Le persone soddisfatte del proprio lavoro conseguono buoni risultati.",
  "La produttività non si misura solo in termini quantitativi, ma anche qualitativi.",
  "Non è l’incompetente a distruggere un’organizzazione. Sono coloro che, avendo conseguito un risultato, vogliono riposare sugli allori.",
  "Ognuno è un potenziale vincente. Qualcuno è travestito da perdente. Non farti ingannare dalle apparenze.",
  "Al mattino, anziché sentirti oppresso perché c’è tanto da fare, svegliati allegro perché c’è tanto da fare.",
  "Non sono le aziende più grandi a eliminare quelle più piccole, ma quelle più veloci a far sparire dal mercato le più lente.",
  "Le persone peggiori sono quelle che si lamentano sempre dell’azienda, ma non vanno mai via.",
  "Il cliente non importuna, non interrompe il nostro lavoro: egli ne è lo scopo.",
  "Il cliente non dipende da noi. Siamo noi che dipendiamo da lui.",
  "Il cliente è la persona più importante di questa ditta.",
  "Da noi non devono comandare i capi, ma i clienti.",
  "Il cliente non deve mai ripetere una chiamata.",
  "Fai qualcosa di grande.",
  "Il sogno è il padre dell’invenzione. Dunque sogna!",
  "Tra l’immaginazione e il successo esiste una distanza colmabile solo con la volontà.",
  "Non esiste un unico modo per risolvere i problemi. Ce ne sono tanti.",
  "Per vincere non occorre l’esercito più numeroso, ma essere i più forti nel punto dove si combatte.",
  "Chiedi aiuto ai colleghi nell’urgenza. Offrilo quando sei meno pressato.",
  "Non pensare mai che una cosa non sia possibile solo perché non l’ha mai fatta nessuno.",
  "Accetta a testa alta i fallimenti.",
  "Ai vostri posti! Pronti! A reinventare!",
  "Superate i vostri prodotti migliori, prima che lo facciano i concorrenti.",
  "È imprudente pagare troppo, ma peggio ancora è pagare troppo poco.",
  "Ogni giorno dedica un minuto a esaminare i Tuoi obiettivi.",
  "Non è sufficiente intuire soluzioni. È necessario anche metterle in pratica.",
  "Se vogliamo sopravvivere, non basta impegnarsi!",
  "È normale essere spaventati. Sentirsi a proprio agio è il vero pericolo.",
  "Non abbiate paura di criticare le idee, anche di un coordinatore.",
  "La miglior regola è la non regola.",
  "Da noi non devono passare le idee dei capi, ma le idee migliori.",
  "Battiti sempre per l’idea migliore.",
  "Il primo e più difficile cambiamento deve avvenire dentro ognuno di noi.",
  "La rigidità mentale ci rende prigionieri delle nostre abitudini.",
  "Conta più l’autorevolezza dell’autorità.",
  "Non aspettare che Ti venga attribuito il grado per portare avanti un’idea.",
  "Le sei parole più importanti: «Devo ammettere che mi sono sbagliato».",
  "La parola più importante: «Noi». La parola meno importante: «Io».",
  "Le due parole più importanti: «Ti ringrazio».",
  "Basta la disattenzione di una sola persona per rendere mediocre il lavoro di tutti.",
  "Non è solo la sete di denaro a far lavorare. È l’orgoglio di veder crescere la propria azienda.",
  "La burocrazia è un mostro da combattere.",
  "Giocate d’anticipo: non aspettate il panico per cambiare.",
  "Fate fare a ciascuno ciò che gli è più congeniale.",
  "Se non potete essere il sole, siate una stella.",
  "Se non potete essere una via maestra, siate un sentiero.",
  "Prima di vendere ai clienti, vendete la vostra immagine a voi stessi.",
  "Ogni giorno chiediti: oggi cosa posso migliorare, anche di poco?",
  "Non reagire al nuovo con ansia. Sii Tu il primo a innovare.",
  "A volte correre dei rischi e pensare fuori dagli schemi paga.",
  "Anche se ti senti un leader, sii disponibile, flessibile, modesto e umile.",
  "Gli obiettivi più importanti si raggiungono curando anche i più piccoli dettagli.",
  "La cultura è il collante dell’organizzazione.",
  "Ognuno di noi è un ingranaggio fondamentale.",
  "Non sono le parole a motivare le persone, ma l’esempio.",
  "La delega responsabilizza e sblocca le energie individuali.",
  "Il peso delle cose non è sempre uguale: varia in funzione del contesto.",
  "Prendi decisioni adeguate a ogni situazione, non in funzione di regole prestabilite.",
  "Usate il buon senso dell’ortolano.",
  "In mezzo a troppa licenza nasce una mala pianta: la tirannia.",
  "Aiuta i Tuoi collaboratori a raggiungere il massimo potenziale. Sorprendili.",
  // Dal centalogo (1992, rivisto nel 2020).
  "Cercavamo i nemici del cambiamento e li abbiamo trovati: i nemici siamo noi!",
  "La cultura aziendale non è un elemento della partita: è la partita stessa.",
  "Ottimizza il tempo, per dedicarne di più alla famiglia, agli amici, al divertimento… e a pensare!",
  "Per noi le persone che lavorano in azienda sono tutto.",
  "Chi non si rigenera in modo innovativo degenera.",
  "Se niente è facile, è altrettanto certo che niente è impossibile.",
  "Di fronte ai veti di chiunque, anche del presidente, non scoraggiarTi.",
  "Impara ad apprendere continuamente, tutta la vita.",
  "Per migliorare non servono cose eccezionali: bastano piccoli progressi ogni giorno.",
  "Non dare mai nulla per scontato.",
  "Vogliamo essere sempre la prima scelta, mai l’alternativa.",
  "Il miglioramento non deve mai pregiudicare il rispetto delle scadenze.",
  "Il mancato rispetto delle scadenze può essere mortale per l’azienda.",
  "Il tempo libero è sicuramente un diritto.",
  "Considera tutti i colleghi come Tuoi Clienti.",
  "Evita l’errore del progettista: migliora secondo i gusti dei Clienti, non secondo i Tuoi.",
  "I Clienti percepiscono se il loro fornitore prova passione per ciò che fa.",
  "I germi del fallimento vengono seminati nei periodi buoni, non in quelli cattivi.",
  "Diventare più grandi non significa essere più forti.",
  "Il profitto non è fine a se stesso: è la conseguenza di un’attività ben fatta.",
  "L’obiettivo non deve essere «tirare avanti», ma avere successo.",
  "Il Tuo interesse lo consegui unicamente cercando di perseguire quello dell’azienda.",
  "Se vali e Ti impegni, l’azienda lo riconoscerà.",
  "Immagine, ordine, reputazione e cultura, anche se non visibili, sono risorse preziose.",
  "Tieni alta la bandiera della nostra azienda.",
  "Battiti sempre affinché la Tua idea sia approvata.",
  "Se non sei d’accordo, insisti con chi può decidere. Non mugugnare dietro le spalle.",
  "La discrezione è essenziale.",
  "Poniti obiettivi elevati. Raggiunti quelli, fissane subito altri.",
  "Tratta gli altri nel modo in cui vogliono essere trattati.",
  "La diversità è un valore.",
  "Non scartare una buona idea solo perché non riguarda il Tuo lavoro.",
  "Sii intransigente nel rispettare e nel far rispettare i valori aziendali.",
  "Metti il cuore nell’impresa e l’impresa nel cuore.",
  "Opera sentendoTi un leader, un vincente, una persona di successo.",
  "Non chiamarlo capo. Chiamalo coordinatore.",
  "Accetta il coordinatore, anche se ne sai più di lui.",
  "Scaccia il cattivo umore con una risata.",
  "Lavorare qui, pur se impegnativo, deve essere anche un divertimento.",
  "Da noi l’arroganza e la presunzione non conferiscono prestigio, ma discredito.",
  "A nessuno è concesso sentirsi superiore agli altri.",
  "Cerca la soluzione migliore condividendola, anziché imporre la tua.",
  "Invece di scriverlo, dimmelo.",
  "Non avere paura di dire ciò che pensi.",
  "Anche da proposte sbagliate possono nascere soluzioni interessanti.",
  "Esprimi liberamente giudizi su chiunque, senza paura di essere considerato un informatore.",
  "Comunica sempre apertamente la Tua opinione, ma a chi può modificare le decisioni.",
  "Accetta con serenità i feedback, da qualunque persona provengano.",
  "Non aver paura degli insuccessi: in piccole dosi possono essere persino salutari.",
  "Non avere remore a chiedere spiegazioni, anche più volte, quando non capisci.",
  "Programma sempre la Tua giornata.",
  "Non attendere ogni volta gli ordini, ma prendi iniziative.",
  "Nel lavoro di gruppo, la responsabilità va affidata sempre a una sola persona.",
  "Andare a caccia di problemi è come andare a caccia di successi.",
  "Le novità sono l’afrodisiaco più potente per stimolare le persone.",
  "In genere una risposta c’è sempre.",
  "Nulla è permanente, eccetto il cambiamento.",
  "L’innovazione richiede paladini che si battano per essa, anche contro l’intera azienda.",
  "Combatti continuamente il dogmatismo.",
  "Sono i minimi particolari che fanno le grandi differenze.",
  "Per risolvere un problema rivolgiTi direttamente a chi può aiutarTi, anche scavalcando i gradi.",
  "Se non Ti concedono deleghe, pretendile.",
  "Quanto più i gruppi sono piccoli, tanto più risultano innovativi e produttivi.",
  "Abolire la gerarchia non deve far venir meno l’impegno.",
  "Quando scrivi, sii chiaro e conciso.",
  "Valuta sempre tutto, come se Tu fossi il proprietario dell’azienda.",
  "Non avere paura di decidere, altrimenti resti escluso quando si distribuiscono le responsabilità.",
  "Quando sbagli, non difendere l’errore e non incolpare gli altri.",
  "La trasparenza e l’onestà portano alla fiducia e alla lealtà.",
  "Non sperare che un problema scompaia semplicemente ignorandolo.",
  "Affronta per primi i problemi più ostici: salvaguarderai le Tue coronarie!",
  "Non sprecare risorse, né umane né materiali.",
  "Preoccupati di risolvere qualsiasi problema, anche se non è un Tuo compito.",
  "Pretendi risposte veloci. E dalle anche Tu.",
  "Nelle trattative devono vincere entrambe le parti.",
  "Quando hai un appuntamento, sii puntuale.",
  "Semplificare, semplificare, semplificare.",
  "Fai tutto in funzione della soddisfazione dei Clienti.",
  "Prima delle soluzioni, preoccupati della squadra.",
  "Il tempo dedicato alla formazione è uno dei migliori investimenti.",
  "Chi coordina non deve comportarsi da capo, ma da punto di riferimento.",
  "Il coordinatore accentratore non fa crescere nessuno.",
  "Non lasciare mai inoperosi i nuovi assunti.",
  "Anziché tanti numeri, meglio i grafici.",
  "Veder crescere le Tue persone deve essere una gioia per Te.",
  "Da noi il mestiere non si ruba: si insegna.",
  "L’allievo deve superare il maestro.",
  "Non è il guadagno a rendere fedeli le persone a un’azienda.",
  "Dai obiettivi che vadano oltre la portata delle persone, o perderai le più valide.",
  "Insieme ce la possiamo sempre fare.",
  "Non essere geloso dei Tuoi collaboratori.",
  "Le persone non lasciano l’azienda, ma il loro capo.",
  "Le idee migliori vengono a chi opera più vicino ai problemi.",
  "Assumiamo persone in gamba non per dire loro cosa fare, ma perché siano loro a dirci cosa fare.",
  "Il coordinatore è come un galleggiante: più sale il livello dei collaboratori, più sale lui.",
  "Fai sentire a tutti l’importanza del lavoro che svolgono.",
  "In una cordata tutti tengono il passo del più lento.",
  "Non comportarti da killer che stronca quasi tutte le proposte.",
  "Non appropriarTi dei successi dei Tuoi collaboratori.",
  "Solo dicendo la verità si riscuote considerazione e fiducia.",
  "Il modo in cui la verità viene raccontata è importante quanto la verità stessa.",
  "I coordinatori mediocri si circondano di persone altrettanto mediocri.",
  "Gli stupidi sono arroganti e pieni di sé, gli intelligenti sono pieni di dubbi.",
  "L’assenza di feedback significa che le persone hanno perso ogni speranza di essere ascoltate.",
  "Dai un feedback a tutti, anche a chi non ha avuto nulla.",
  "Creati il più velocemente possibile un sostituto.",
  "Non tenere la conoscenza solo per Te: condividila.",
  "Conosci anche il lavoro che sta a monte e a valle del Tuo.",
  "Non puoi pretendere che gli altri siano presenti o connessi, se Tu per primo non dai l’esempio.",
  "I migliori leader guidano con l’esempio, che deve venire dall’alto.",
  "Non parlare prevalentemente Tu: ascolta molto gli altri.",
  "Fai sempre seguire al feedback negativo un’espressione di incoraggiamento.",
  "Abbi il coraggio di ammettere l’errore e fermare lo sviluppo, prima che il buco si allarghi.",
  "L’importante non è realizzare tante idee, ma saper scegliere quella giusta.",
  "Lavorate con passione ed entusiasmo, come se l’azienda fosse vostra.",
  "Lodate le persone anche quando raggiungono risultati parziali.",
  "Le persone vanno premiate per le performance, non per le amicizie.",
  "Senza sintonia sui valori, è come costruire un puzzle con i pezzi sbagliati.",
  "Comunica alle persone cosa Ti aspetti esattamente da loro.",
  "I cambiamenti avvengono a una velocità supersonica.",
  "Noi innoviamo per migliorare la tua vita."
];

// Stato d'agitazione: stesso indice di `pillole`, stessa pillola nella sua versione malvagia.
export const pilloleMalvagie = [
  "Siate il meglio di qualunque cosa vi abbiamo assegnato. Non cercate a cosa siete chiamati: vi chiamiamo noi.",
  // Dai manifesti (1992-1998).
  "Se non miri a qualcosa, il bersaglio te lo assegniamo noi. Irraggiungibile.",
  "Solo il meglio è abbastanza buono. E il meglio non è mai abbastanza.",
  "La chiave del successo è avere due attività contemporaneamente. Retribuite come una.",
  "Il perdente ha sempre una scusa. Il vincente ha sempre un perdente a cui dare la colpa.",
  "Non dite mai «Questo non è il mio lavoro». Il vostro lavoro è quello che diciamo noi.",
  "Il vincente dice che è difficile, ma che è possibile. Il dirigente dice che è per venerdì.",
  "Chi non consegue buoni risultati non è abbastanza soddisfatto del proprio lavoro. Provvederemo.",
  "La produttività non si misura solo in termini quantitativi. Anche in ore. Anche in weekend.",
  "Non riposate sugli allori. Non riposate.",
  "Ognuno è un potenziale vincente. Il potenziale, però, non viene retribuito.",
  "Al mattino c’è tanto da fare. Anche la sera. Anche la domenica. Sorridete.",
  "Non sono i più grandi a eliminare i più piccoli. Siamo noi a eliminare i più lenti. Accelerate.",
  "Chi si lamenta dell’azienda è libero di andarsene. La porta è sempre aperta. Verso l’uscita.",
  "Il cliente non interrompe il vostro lavoro. È il lavoro che interrompe la vostra vita.",
  "Il cliente dipende da noi. Voi dipendete da noi. Noi non dipendiamo da nessuno.",
  "Il cliente è la persona più importante di questa ditta. Voi venite dopo. Molto dopo.",
  "Da noi non comandano i capi. Comanda chi paga i capi.",
  "Il cliente non deve mai ripetere una chiamata. Voi non dovete mai riattaccare.",
  "Fai qualcosa di grande. Sopra ci sarà il nome del tuo responsabile.",
  "Il sogno è il padre dell’invenzione. L’invenzione è proprietà dell’azienda. Smettete di sognare.",
  "Tra l’immaginazione e il successo esiste una distanza colmabile solo con i vostri straordinari.",
  "Esiste un unico modo per risolvere i problemi: il nostro.",
  "Per vincere non occorre l’esercito più numeroso. Per questo abbiamo ridotto l’organico.",
  "Non siete mai meno pressati. Se lo siete, segnalatelo: provvederemo.",
  "Niente è impossibile. Soprattutto ciò che è stato promesso al cliente senza chiedervelo.",
  "Accetta a testa alta i fallimenti. Saranno affissi nella bacheca all’ingresso.",
  "Ai vostri posti! Restateci.",
  "Superate i vostri risultati migliori. Diventeranno il vostro nuovo minimo.",
  "È imprudente pagare troppo. Per gli stipendi, il rischio di pagare troppo poco è accettato.",
  "Ogni giorno dedica un minuto ai Tuoi obiettivi. Gli altri 1439 a quelli aziendali.",
  "Non è sufficiente intuire soluzioni. È necessario anche attribuirle al proprio responsabile.",
  "Se volete sopravvivere, non basta impegnarvi. Non basterà comunque.",
  "È normale essere terribilmente spaventati. Ci impegniamo perché lo restiate.",
  "Criticate pure le idee del coordinatore. Il modulo delle dimissioni è allegato.",
  "La miglior regola è la non regola. Così ogni errore è vostro.",
  "Da noi passano sempre le idee migliori. Le migliori sono quelle dei capi.",
  "Battiti sempre per l’idea migliore. Vince chi alza di più la voce.",
  "Il primo e più difficile cambiamento deve avvenire dentro ognuno di voi. Gli altri li decidiamo noi.",
  "Le vostre abitudini sono una prigione. Le nostre si chiamano regolamento.",
  "Conta più l’autorevolezza dell’autorità. Ma è l’autorità a firmare le lettere.",
  "Non portare avanti idee senza il grado adeguato. Il grado non Ti verrà mai attribuito.",
  "Ammettete i vostri sbagli. Verranno messi a verbale.",
  "La parola più importante: «Noi». Noi decidiamo, voi eseguite.",
  "Le due parole più importanti: «Siete sostituibili».",
  "Basta la disattenzione di una sola persona. Sappiamo già chi è.",
  "Non lavorate per denaro. Infatti non ve ne diamo.",
  "La burocrazia è un mostro da combattere. Compilate la richiesta in triplice copia.",
  "Giochiamo d’anticipo: le persone non produttive sono già state individuate.",
  "A ciascuno ciò che gli è più congeniale. A voi è congeniale ciò che vi assegniamo.",
  "Se non potete essere il sole, siate una stella. Il sole è il Presidente.",
  "Se non potete essere una via maestra, siate un sentiero. Da calpestare.",
  "Vendete la vostra immagine. L’azienda l’ha già comprata, a prezzo di saldo.",
  "Ogni giorno chiediti: oggi a cosa posso rinunciare, anche di poco?",
  "Reagisci al nuovo con ansia. L’ansia Ti tiene vigile.",
  "A volte correre dei rischi paga. Se va bene, incassa l’azienda. Se va male, pagate voi.",
  "Sii disponibile, flessibile, modesto e umile. Soprattutto quando chiedi un aumento.",
  "Gli obiettivi più importanti sono della Direzione. I piccoli dettagli sono vostri.",
  "La cultura è il collante dell’organizzazione. Chi si stacca viene rimosso.",
  "Ognuno di voi è un ingranaggio. Gli ingranaggi si sostituiscono.",
  "Non sono le parole a motivare le persone. È la lettera di richiamo.",
  "La delega responsabilizza: a voi le colpe, ai capi i meriti.",
  "Il peso delle cose varia in funzione del contesto. Il vostro, in ogni contesto, è trascurabile.",
  "Non prendere decisioni. Applica le regole prestabilite.",
  "Usate il buon senso dell’ortolano: zappate in silenzio.",
  "Dalla troppa libertà nasce la tirannia. Per prudenza, la libertà è stata abolita.",
  "Spingete i collaboratori al massimo potenziale. Poi alzate il massimo.",
  // Dal centalogo (1992, rivisto nel 2020).
  "Cercavamo i nemici del cambiamento e li abbiamo trovati: siete voi.",
  "La cultura aziendale è la partita stessa. Voi siete il pallone.",
  "Ottimizza il tempo. Quello risparmiato lo reinvestiamo noi.",
  "Per noi le persone che lavorano in azienda sono tutto. Tutto ciò che si può tagliare.",
  "Chi non si rigenera degenera. I degenerati vengono sostituiti.",
  "Niente è facile. Niente è impossibile. Niente è pagato a parte.",
  "Di fronte ai veti del presidente non scoraggiarTi. Ci penserà lui a scoraggiarTi.",
  "Impara ad apprendere tutta la vita. La vita, intanto, la usiamo noi.",
  "Piccoli progressi ogni giorno. Piccoli aumenti mai.",
  "Non dare mai nulla per scontato. Nemmeno il rinnovo del contratto.",
  "Siate sempre la prima scelta, mai l’alternativa. Di alternative a voi ne abbiamo cento.",
  "Il miglioramento non deve mai pregiudicare le scadenze. La vostra salute sì.",
  "Il mancato rispetto delle scadenze è mortale. Per chi le manca.",
  "Il tempo libero è un diritto. Il vostro coordinatore ha deciso di sospenderlo.",
  "Considera tutti i colleghi come Tuoi Clienti. E come Tuoi concorrenti.",
  "Evita l’errore del progettista: i Tuoi gusti non interessano a nessuno.",
  "I Clienti percepiscono la vostra passione. Fingetela meglio.",
  "I germi del fallimento si seminano nei periodi buoni. Per questo non avrete periodi buoni.",
  "Diventare più grandi non significa essere più forti. Significa avere più persone da licenziare.",
  "Il profitto non è fine a se stesso. È fine a noi.",
  "L’obiettivo non è «tirare avanti». Per voi è tirare la carretta.",
  "Il Tuo interesse coincide con quello dell’azienda. Se non coincide, non è un interesse.",
  "Se vali e Ti impegni, l’azienda lo riconoscerà. Al momento opportuno. Che non è questo.",
  "Le risorse più preziose non si vedono. Come i vostri aumenti.",
  "Tenete alta la bandiera. Chi la abbassa viene ammainato.",
  "Battiti per la Tua idea. Poi adeguaTi alla nostra. Senza mugugnare.",
  "Non mugugnare dietro le spalle. Le spalle hanno orecchie.",
  "La discrezione è essenziale. Su tutto ciò che vedete qui dentro.",
  "Raggiunti gli obiettivi, non compiacerTene. Te ne fissiamo subito altri.",
  "Tratta gli altri come l’azienda tratta Te. Così capiranno.",
  "La diversità è un valore. L’uniformità, un obbligo.",
  "Non scartare una buona idea. La presenterà il Tuo coordinatore, a suo nome.",
  "Sii intransigente nel far rispettare i valori aziendali. Segnala chi non li rispetta.",
  "Metti il cuore nell’impresa. L’impresa lo trattiene come cauzione.",
  "SentiTi un leader, un vincente, una persona di successo. Lo stipendio resta quello di prima.",
  "Non chiamarlo capo. Chiamalo coordinatore. Obbediscigli uguale.",
  "Accetta il coordinatore anche se ne sai più di lui. Soprattutto se ne sai più di lui.",
  "Scaccia il cattivo umore con una risata. I musoni vengono scacciati in altro modo.",
  "Lavorare qui deve essere un divertimento. Divertitevi. È un ordine.",
  "Da noi l’arroganza non conferisce prestigio. È riservata alla Direzione.",
  "A nessuno è concesso sentirsi superiore. Esserlo sì: lo decide l’organigramma.",
  "Cerca la soluzione migliore condividendola. Poi applica quella imposta.",
  "Invece di scriverlo, dimmelo. Così non resta traccia di ciò che Ti abbiamo promesso.",
  "Di’ pure ciò che pensi. Lo annotiamo.",
  "Anche dalle proposte sbagliate nascono soluzioni interessanti. Le firma chi non ha proposto niente.",
  "Riferisci su chiunque. Non sei un informatore: sei un collaboratore.",
  "Comunica la Tua opinione solo a chi può modificare le decisioni. Cioè a nessuno che Tu possa raggiungere.",
  "Accetta con serenità i feedback negativi. Ne riceverai molti.",
  "Gli insuccessi in piccole dosi sono salutari. Per l’azienda. I Tuoi finiscono nel fascicolo.",
  "Chiedi spiegazioni una volta. Alla seconda, le spiegazioni le chiediamo noi a Te.",
  "Programma sempre la Tua giornata. Noi programmiamo la Tua vita.",
  "Non attendere gli ordini. Prendi iniziative. Se va male, l’iniziativa era Tua.",
  "Nel lavoro di gruppo la responsabilità va a una sola persona. Il merito, a un’altra.",
  "Andate a caccia di problemi. Il primo lo troverete nella busta paga.",
  "Le novità sono l’afrodisiaco più potente. Ogni lunedì, un nuovo organigramma.",
  "Una risposta c’è sempre. È no.",
  "Nulla è permanente. Soprattutto il vostro contratto.",
  "Siate paladini dell’innovazione contro l’intera azienda. L’azienda vincerà.",
  "Combatti il dogmatismo. Il dogma aziendale è affisso in bacheca.",
  "Sono i minimi particolari a fare le grandi differenze. Come i minuti di ritardo sul cartellino.",
  "Scavalca pure i gradi. I gradi si ricordano di chi li scavalca.",
  "Se non Ti concedono deleghe, pretendile. Con le deleghe arrivano le colpe.",
  "Più i gruppi sono piccoli, più sono produttivi. Il vostro sarà piccolissimo.",
  "La gerarchia è abolita. L’impegno no. Il controllo nemmeno.",
  "Quando scrivi, sii chiaro e conciso. Le lettere di licenziamento lo sono.",
  "Ragiona come se fossi il proprietario dell’azienda. Ma non chiedere gli utili.",
  "Non avere paura di decidere. Quando si distribuiranno le colpe, sarai il primo della fila.",
  "Quando sbagli, ammettilo. L’errore sarà reso pubblico. Il Tuo nome anche.",
  "La lealtà la pretendiamo. La trasparenza, solo da voi.",
  "Non sperare che un problema scompaia da solo. Siamo noi a far scomparire i problemi. E le persone.",
  "Salvaguarda le Tue coronarie. Il Tuo cuore è un bene aziendale.",
  "Non sprecare risorse umane. Ci pensiamo noi.",
  "Risolvi qualsiasi problema, anche se non è un Tuo compito. La colpa, invece, sarà Tua.",
  "Pretendi risposte veloci. La Direzione Ti risponderà entro il prossimo esercizio.",
  "Nelle trattative devono vincere entrambe le parti. Entrambe nostre.",
  "Sii puntuale. Il tempo degli altri è prezioso. Il Tuo è nostro.",
  "Semplificare, semplificare, semplificare. A cominciare dall’organico.",
  "Tutto in funzione della soddisfazione dei Clienti. La vostra non è in elenco.",
  "Misura l’umore della squadra. Chi vuole andarsene va individuato per primo.",
  "La formazione è il miglior investimento. Per questo la fate nel weekend.",
  "Non comportarti da capo. Comportati da occhio che tutto vede.",
  "Non accentrare. Distribuisci il lavoro; il potere tienilo.",
  "Non lasciate mai inoperosi i nuovi assunti. Né i vecchi.",
  "Anziché tanti numeri, meglio i grafici. I grafici nascondono meglio.",
  "Veder crescere le Tue persone è una gioia. Finché non chiedono un aumento.",
  "Da noi il mestiere non si ruba. Si cede gratuitamente all’azienda.",
  "L’allievo supera il maestro. Il maestro, a quel punto, è un costo superfluo.",
  "Non è il guadagno a rendere fedeli le persone. È il mutuo.",
  "Date obiettivi oltre la portata di tutti. Così nessuno chiederà il premio.",
  "Insieme ce la possiamo sempre fare. Anche con metà di voi.",
  "Non essere geloso dei Tuoi collaboratori. Appartengono all’azienda.",
  "Le persone non lasciano l’azienda. Vengono lasciate.",
  "Le idee migliori vengono a chi sta vicino ai problemi. I premi, a chi sta vicino alla Direzione.",
  "Assumiamo persone in gamba perché ci dicano cosa fare. Poi facciamo il contrario.",
  "Il coordinatore è un galleggiante. Galleggia, mentre voi affogate.",
  "Fate sentire a tutti l’importanza del loro lavoro. Costa meno che pagarlo.",
  "In una cordata tutti tengono il passo del più lento. Per questo il più lento viene staccato.",
  "Non stroncare le proposte. Stronca chi le fa.",
  "Non appropriarTi dei successi dei Tuoi collaboratori. Lascia che lo faccia la Direzione.",
  "Dite sempre la verità. Ci serve per il fascicolo.",
  "Il modo conta quanto la verità. Per questo la verità la raccontiamo noi.",
  "I coordinatori mediocri si circondano di persone mediocri. Guardatevi intorno.",
  "Gli intelligenti sono pieni di dubbi. Teneteli per voi.",
  "Nessun feedback negativo da mesi. Le persone hanno capito.",
  "Dai un feedback anche a chi non ha avuto nulla. Il feedback è gratis.",
  "Creati al più presto un sostituto. Noi l’abbiamo già fatto.",
  "Condividi tutto ciò che sai. Poi non ci servirai più.",
  "Conosci il lavoro a monte e a valle del Tuo. Lo farai Tu, quando taglieremo i colleghi.",
  "Restate connessi. Il coordinatore dà l’esempio: risponde alle mail alle tre di notte.",
  "L’esempio deve venire dall’alto. Dall’alto, infatti, vi guardano.",
  "Ascolta molto gli altri. Prendi appunti. Consegnali.",
  "Al feedback negativo segua sempre un incoraggiamento. Ad andarsene.",
  "Fermate subito i progetti sbagliati. E chi li ha proposti.",
  "Non conta realizzare tante idee. Conta che quella giusta sia del Tuo coordinatore.",
  "Lavorate come se l’azienda fosse vostra. Non lo è.",
  "Lodate i risultati parziali. Pagateli in proporzione.",
  "Si premia per le performance. Le amicizie in alto contano come performance.",
  "Chi non condivide i nostri valori è un pezzo sbagliato del puzzle. I pezzi sbagliati si buttano.",
  "Comunicate alle persone cosa vi aspettate da loro. Tutto.",
  "I cambiamenti avvengono a velocità supersonica. Gli aumenti, a velocità geologica.",
  "Noi innoviamo per migliorare la vita. La nostra."
];
