// Pillole di tutti i giorni.
export const pillole = [
  "Non aspettate il momento perfetto. Createne uno.",
  "Ogni sfida è un’opportunità mascherata da ostacolo.",
  "Non fate solo il vostro dovere. Fate la differenza.",
  "La passione è il motore. La costanza è la strada.",
  "Non temete di sbagliare. Temete di non provare.",
  "Siate curiosi. La curiosità è il primo passo verso il cambiamento.",
  "Il successo non è una destinazione. È un’attitudine.",
  "Non lavorate solo per un obiettivo. Lavorate per un significato.",
  "Ogni giorno è una scelta. Scegliete di essere eccellenti.",
  "Non aspettate che qualcuno vi motivi. Siate la vostra ispirazione.",
  "Non siate solo parte del cambiamento. Siate il motivo per cui accade.",
  "Il talento è un dono. La disciplina è una scelta.",
  "Non cercate la strada più facile. Cercate quella che vi migliora.",
  "Ogni errore è un maestro che parla a chi sa ascoltare.",
  "Non lavorate per il successo. Lavorate per il valore.",
  "La vera innovazione nasce dove finisce la comodità.",
  "Non siate reattivi. Siate proattivi.",
  "Il tempo è limitato. Usatelo per costruire, non per sopravvivere.",
  "Non aspettate di avere tutto. Iniziate con ciò che avete.",
  "La leadership non è un titolo. È un esempio.",
  "Non cercate di piacere a tutti. Cercate di essere autentici.",
  "Il futuro non si prevede. Si crea.",
  "Non temete la fatica. Temete la stagnazione.",
  "La crescita inizia dove finisce la zona di comfort.",
  "Non fate le cose perché vanno fatte. Fatele perché ci credete.",
  "Il successo è la somma di piccoli sforzi ripetuti ogni giorno.",
  "Non siate spettatori della vostra vita. Siate i protagonisti.",
  "La passione è contagiosa. Diffondetela.",
  "Non cercate scuse. Cercate soluzioni.",
  "Il mondo cambia quando cambiate il vostro modo di vederlo.",
  "Non accontentatevi di essere bravi. Puntate a essere unici.",
  "La vera forza è restare gentili in un mondo che non lo è sempre.",
  "Non cercate il perché del fallimento. Cercate il come della ripartenza.",
  "Il talento vi porta in alto. Il carattere vi mantiene lì.",
  "Non fate le cose per doverle fare. Fatele perché vi rappresentano.",
  "Ogni giorno è una nuova possibilità. Non sprecatela.",
  "Non temete di essere diversi. Temete di essere uguali a tutti.",
  "La vera competizione è con voi stessi. Ogni giorno, un passo in più.",
  "Non aspettate che qualcosa cambi. Siate voi il cambiamento.",
  "La conoscenza è potere. La saggezza è responsabilità.",
  "Non cercate di fare tutto. Cercate di fare bene ciò che conta.",
  "Il coraggio non è non avere paura. È agire nonostante la paura.",
  "Non siate solo efficienti. Siate ispiranti.",
  "La vera eccellenza è fare le cose semplici in modo straordinario.",
  "Non lavorate per un posto. Lavorate per una missione.",
  "Il successo è una conseguenza. La dedizione è la causa.",
  "Non cercate di essere perfetti. Cercate di essere migliori di ieri.",
  "La vera ricchezza è fare ciò che amate e sapere perché lo fate.",
  "Non temete il giudizio. Temete di non essere fedeli a voi stessi.",
  "La passione crea strade dove la logica vede muri.",
  "Non siate solo parte di un team. Siate la sua energia.",
  "Il valore di ciò che fate è nel perché lo fate.",
  "Non cercate di fare tutto da soli. Cercate di fare insieme ciò che conta.",
  "La vera integrità è fare la cosa giusta anche quando nessuno guarda.",
  "Non siate solo veloci. Siate consapevoli.",
  "Il lavoro non è solo produrre. È creare impatto.",
  "Non cercate di piacere a tutti. Cercate di essere utili a qualcuno.",
  "La vera innovazione è il coraggio di pensare diversamente.",
  "Non fate solo quello che vi viene chiesto. Fate quello che serve.",
  "La vostra voce ha valore. Usatela per costruire.",
  "Non aspettate l’ispirazione. Createla con le azioni.",
  "La vera competenza è sapere quando imparare di nuovo.",
  "Non fate solo domande. Siate la risposta che serve.",
  "Il successo non è una meta. È un modo di vivere.",
  "Non cercate di essere i migliori. Cercate di essere utili.",
  "La vera crescita è quando il comfort lascia spazio alla scoperta.",
  "Non temete di ricominciare. Ogni inizio è una nuova forza.",
  "Il lavoro è un luogo di valori. Non solo di compiti.",
  "Non cercate la perfezione. Cercate l’evoluzione.",
  "La vera motivazione nasce dal perché, non dal come.",
  "Non siate solo presenti. Siate coinvolti.",
  "Il tempo è un investimento. Usatelo per costruire futuro.",
  "Non fate le cose per abitudine. Fatele per convinzione.",
  "La vera eccellenza è fare il proprio meglio anche quando nessuno guarda.",
  "Non cercate di controllare tutto. Cercate di dare il meglio in ogni cosa.",
  "Il cambiamento non si aspetta. Si guida.",
  "Non siate solo esecutori. Siate ideatori.",
  "La vera leadership è servire, non comandare.",
  "Non temete di essere imperfetti. Temete di non essere reali.",
  "Il valore di una persona non sta in ciò che fa, ma in come lo fa.",
  "Non cercate di evitare i problemi. Cercate di risolverli con intelligenza.",
  "La vera influenza è l’esempio che date, non le parole che usate.",
  "Non siate solo strumenti. Siate visioni in azione.",
  "Il successo è un viaggio che inizia con la scelta di crederci.",
  "Non cercate di fare tutto. Cercate di fare ciò che conta.",
  "La vera motivazione è sapere per chi e perché lo fai.",
  "Non temete il cambiamento. Temete la resistenza a crescere.",
  "Il lavoro è un’opportunità per lasciare un segno.",
  "Non cercate di essere invisibili. Cercate di essere indimenticabili.",
  "La vera passione non si dichiara. Si dimostra.",
  "Non cercate di fare rumore. Cercate di lasciare un’eco.",
  "La vera professionalità è unire competenza e cuore.",
  "Non siate solo risultati. Siate relazioni.",
  "Il valore di un’azienda è nelle persone che la vivono.",
  "Non cercate di essere indispensabili. Cercate di essere indimenticabili.",
  "La vera cultura aziendale si costruisce con ogni gesto quotidiano.",
  "Non temete di cambiare rotta. Temete di non avere una direzione.",
  "Il lavoro è un’espressione di chi siete. Fatene un’opera.",
  "Non cercate di fare la differenza. Siate la differenza.",
  "Siate il meglio di qualunque cosa siate. Cercate ardentemente di scoprire a cosa siete chiamati, poi mettetevi a farlo appassionatamente."
];

// Stato d'agitazione: stesso indice di `pillole`, stessa pillola nella sua versione malvagia.
export const pilloleMalvagie = [
  "Non aspettate il momento perfetto per chiedere un aumento. Non arriverà mai.",
  "Ogni sfida è un’opportunità per noi. Ogni ostacolo è un problema vostro.",
  "Non fate solo il vostro dovere. Fate anche quello del collega licenziato.",
  "La passione è il motore. Il vostro stipendio è il carburante che risparmiamo.",
  "Non temete di sbagliare. Temete che la Direzione lo venga a sapere.",
  "Non siate curiosi. La curiosità è il primo passo verso il provvedimento disciplinare.",
  "Il successo non è una destinazione. È il bonus che riceverà il vostro dirigente.",
  "Non lavorate per un significato. Lavorate per il dividendo degli azionisti.",
  "Ogni giorno è una scelta. Scegliete di restare oltre l’orario, o scegliete l’uscita.",
  "Non aspettate che qualcuno vi motivi. La paura del licenziamento è motivazione sufficiente.",
  "Non siate parte del cambiamento. Il cambiamento è già stato deciso, in vostra assenza.",
  "Il talento è un dono. La disciplina è obbligatoria.",
  "Non cercate la strada più facile. Quella è riservata al consiglio di amministrazione.",
  "Ogni errore è annotato nel vostro fascicolo personale. Per sempre.",
  "Non lavorate per il successo. Lavorate per il valore. Il valore per l’azionista.",
  "La vera innovazione nasce dove finisce la vostra comodità. E il vostro riposo.",
  "Non siate reattivi. Siate proattivi. Anticipate le nostre richieste, anche nel weekend.",
  "Il vostro tempo è limitato. Per questo ce lo prendiamo tutto.",
  "Non aspettate di avere gli strumenti. Iniziate con ciò che avete: niente.",
  "La leadership non è un titolo. È il diritto di dare la colpa a voi.",
  "Non cercate di essere autentici. Cercate di essere conformi.",
  "Il futuro non si prevede. Si decide ai piani alti. Il vostro non è in agenda.",
  "Non temete la fatica. Temete la riorganizzazione.",
  "La crescita del fatturato inizia dove finisce la vostra pausa pranzo.",
  "Non fate le cose perché ci credete. Fatele perché sono state ordinate.",
  "Il successo è la somma di piccoli straordinari non retribuiti, ripetuti ogni giorno.",
  "Non siete i protagonisti della vostra vita. Siete risorse. Risorse sostituibili.",
  "La passione è contagiosa. Anche il dissenso: segnalatelo.",
  "Non cercate scuse. Non cercate soluzioni. Timbrate il cartellino.",
  "Il mondo non cambia. Cambia solo la vostra capacità di accettarlo.",
  "Non accontentatevi di essere bravi. Accontentatevi del vostro stipendio.",
  "La vera forza è restare gentili mentre vi tagliamo i buoni pasto.",
  "Non cercate il perché del fallimento. Il colpevole è già stato individuato: voi.",
  "Il talento vi porta in alto. Il carattere vi fa notare. Farsi notare è sconsigliato.",
  "Non fate le cose perché vi rappresentano. Voi non siete rappresentati.",
  "Ogni giorno è una nuova possibilità di produrre di più per lo stesso compenso.",
  "Non temete di essere uguali a tutti. Temete di essere diversi. I diversi vengono notati.",
  "La vera competizione è con il collega accanto. Ogni trimestre, uno di voi in meno.",
  "Non aspettate che qualcosa cambi. Nulla cambierà.",
  "La conoscenza è potere. Per questo vi diciamo solo lo stretto necessario.",
  "Non cercate di fare bene ciò che conta. Fate tutto. Subito. Da soli.",
  "Il coraggio non è non avere paura. È chiedere le ferie ad agosto.",
  "Non siate ispiranti. Siate efficienti. L’ispirazione non compare a bilancio.",
  "La vera eccellenza è fare cose straordinarie con uno stipendio ordinario.",
  "Non lavorate per un posto. Il posto non è garantito. La missione sì: la nostra.",
  "Il successo è dell’azienda. La dedizione è vostra. Non confondete le due cose.",
  "Non cercate di essere migliori di ieri. Siate migliori del collega che stiamo valutando.",
  "La vera ricchezza è fare ciò che amate. Per questo non vi serve quella in busta paga.",
  "Non temete il giudizio. Il giudizio è continuo, anonimo e inappellabile.",
  "La passione crea strade dove la logica vede muri. I muri, comunque, sono sorvegliati.",
  "Non siate solo parte di un team. Siate la sua energia: rinnovabile e a costo zero.",
  "Il valore di ciò che fate lo stabiliamo noi. E non è molto.",
  "Non cercate di fare insieme. Le riunioni non autorizzate sono vietate.",
  "La vera integrità è fare la cosa giusta anche quando nessuno guarda. Ma noi guardiamo sempre.",
  "Non siate consapevoli. Siate solo veloci.",
  "Il lavoro non è solo produrre. È produrre di più.",
  "Non cercate di essere utili a qualcuno. Siate utili a noi.",
  "Pensare diversamente è un sintomo. Rivolgetevi alle Risorse Umane.",
  "Non fate solo quello che vi viene chiesto. Fate anche quello che non vi verrà pagato.",
  "La vostra voce non ha valore. Usatela solo per dire sì.",
  "Non aspettate l’ispirazione. Aspettate istruzioni.",
  "La vera competenza è imparare di nuovo. Fuori orario, a vostre spese.",
  "Non fate domande. Le domande rallentano la produzione.",
  "Il successo non è un modo di vivere. Il lavoro sì. Non ne esiste un altro.",
  "Non cercate di essere i migliori. Cercate di non essere i prossimi.",
  "La vera crescita è quando il comfort lascia spazio al vostro nuovo carico di lavoro.",
  "Non temete di ricominciare. Con il nuovo contratto, ricomincerete dal livello più basso.",
  "Il lavoro è un luogo di compiti. I valori sono quotati in borsa.",
  "Non cercate la perfezione. Cercate la produttività. La perfezione costa troppo.",
  "La vera motivazione nasce dal perché. Il perché è: altrimenti siete fuori.",
  "Non siate solo presenti. Siate reperibili. Sempre.",
  "Il vostro tempo è un investimento. Il rendimento lo incassiamo noi.",
  "Non fate le cose per convinzione. Fatele per abitudine. L’abitudine non protesta.",
  "La vera eccellenza è dare il meglio anche quando nessuno guarda. Tanto qualcuno guarda.",
  "Non cercate di controllare tutto. Il controllo spetta a noi.",
  "Il cambiamento non si guida. Si subisce. In silenzio.",
  "Non siate ideatori. Siate esecutori. Le idee sono di proprietà dell’azienda.",
  "La vera leadership è comandare. Servire è compito vostro.",
  "Non temete di essere imperfetti. Temete la valutazione annuale.",
  "Il valore di una persona sta in quanto produce per ora lavorata.",
  "Non cercate di risolvere i problemi. Il problema siete voi.",
  "La vera influenza è il silenzio che otteniamo, non le parole che usate.",
  "Non siete visioni in azione. Siete strumenti. Strumenti ammortizzabili.",
  "Il successo è un viaggio che inizia con la firma di una clausola di non concorrenza.",
  "Non cercate di fare ciò che conta. Fate tutto. Conta tutto.",
  "La vera motivazione è sapere per chi lo fate: per qualcuno che non incontrerete mai.",
  "Non temete il cambiamento. Temete la resistenza: viene registrata.",
  "Il lavoro è un’opportunità per lasciare un segno. Sulla vostra salute.",
  "Non cercate di essere indimenticabili. Cercate di essere invisibili. Gli invisibili non vengono tagliati.",
  "La vera passione non si dichiara. Si dimostra con gli straordinari.",
  "Non cercate di fare rumore. Il rumore è perseguibile.",
  "La vera professionalità è unire competenza e cuore. Il cuore, possibilmente, a fine turno.",
  "Non siate relazioni. Siate risultati. Le relazioni non si fatturano.",
  "Il valore di un’azienda è nelle persone che la vivono. Fino al prossimo taglio del personale.",
  "Non cercate di essere indispensabili. Nessuno lo è.",
  "La vera cultura aziendale si costruisce con ogni gesto quotidiano. E ogni gesto quotidiano è registrato.",
  "Non temete di cambiare rotta. La rotta la decidiamo noi.",
  "Il lavoro non è un’espressione di chi siete. Voi siete ciò che il lavoro esige.",
  "Non siate la differenza. Siate la media. Sotto la media, siete il prossimo esubero.",
  "Siate il meglio di qualunque cosa vi abbiamo assegnato. Non cercate a cosa siete chiamati: vi chiamiamo noi."
];
