// Pillole natalizie (8 dicembre - 6 gennaio).
export const pillole = [
  "A Natale, non puntiamo solo ai risultati: diventiamo il valore aggiunto nelle vite degli altri.",
  "La magia del Natale è credere che ogni piccolo gesto possa generare un impatto significativo.",
  "La generosità non ha KPI: praticatela ogni giorno come fosse parte della strategia.",
  "Il vero spirito natalizio è creare spazio per gli altri, proprio come facciamo per idee e opportunità.",
  "A Natale, la gentilezza è il nostro personal branding migliore.",
  "Non cercate luci esterne: siate il faro che guida stakeholder e persone vicine.",
  "Il regalo più prezioso è il tempo investito in relazioni che generano valore.",
  "A Natale, non si tratta di avere di più, ma di *essere più* per la comunità che costruiamo.",
  "La festa inizia quando attiviamo il nostro mindset aperto e collaborativo.",
  "Non servono fiocchi: l’autenticità è il packaging più potente.",
  "A Natale, ogni sorriso è una micro-azione che illumina il percorso condiviso.",
  "Il calore delle feste nasce da comunicazioni sincere e connessioni autentiche.",
  "Non serve la neve: basta la predisposizione ad accogliere con un mindset positivo.",
  "A Natale, la gratitudine è il collante che rafforza ogni partnership e relazione.",
  "Il vero spirito natalizio è fare il bene senza aspettare una call to action.",
  "Non cercate il Natale sugli scaffali: trovatelo nei valori che mettiamo in pratica.",
  "Ogni Natale è una milestone per ripartire con più consapevolezza e meno frenesia.",
  "A Natale, il valore non è ciò che riceviamo, ma ciò che scegliamo di condividere.",
  "La bellezza del Natale è ricordarci quanto sia strategico esserci, davvero.",
  "Non servono grandi progetti: basta presenza autentica per fare la differenza.",
  "A Natale, la leadership si misura nella capacità di ispirare attraverso l’esempio.",
  "Il Natale è il touchpoint ideale per riscoprire il valore della gentilezza.",
  "Non fate tutto: fate spazio a ciò che contribuisce davvero agli obiettivi comuni.",
  "A Natale, ogni gesto gentile è una scintilla che alimenta l’energy del team.",
  "Il vero dono è essere presenti, ascoltare attivamente e creare connessioni.",
  "A Natale, la differenza la fa chi sceglie di essere luce nel percorso formativo di qualcun altro.",
  "Non aspettate il cenone: celebrate ogni micro-successo e ogni gesto di cura.",
  "Il Natale è un prompt per rallentare, riflettere e riallinearsi con i nostri valori.",
  "A Natale, non siate spettatori: siate generatori di impatto positivo.",
  "La vera eccellenza natalizia è fare il bene senza bisogno di metriche o visibilità.",
  "A Natale, trasformiamo ogni gesto in un’opportunità di generare valore condiviso.",
  "Il periodo natalizio è il contesto ideale per abilitare nuove sinergie umane.",
  "A Natale, coltiviamo relazioni che supportano il nostro ecosistema di persone.",
  "Il vero regalo è investire in un mindset orientato alla cura e alla collaborazione.",
  "A Natale, la nostra vision si traduce in piccoli gesti che creano grande impatto.",
  "Il Natale è il momento perfetto per fare un refresh del nostro purpose personale.",
  "Ogni gesto natalizio è un touchpoint che rafforza la nostra cultura umana e professionale.",
  "A Natale, scegliamo di essere partner di fiducia per chi ci circonda.",
  "Il valore delle feste nasce da connessioni basate su empatia e ascolto attivo.",
  "A Natale, attiviamo un approccio più umano al nostro percorso di crescita.",
  "La magia delle feste è un reminder di quanto sia importante mettere le persone al centro.",
  "A Natale, ogni parola diventa una leva di ispirazione e benessere condiviso.",
  "Il vero spirito natalizio è creare opportunità, non aspettare che arrivino.",
  "In questo periodo, modelliamo un ambiente che favorisce la collaborazione autentica.",
  "A Natale, l’impatto più grande nasce dai gesti che nessuno vede.",
  "Ogni festa è un’occasione per evolvere il nostro modo di essere presenti.",
  "A Natale, allineiamo le nostre priorità a ciò che genera valore reale.",
  "Il Natale ci invita a praticare una leadership gentile e rigenerativa.",
  "In questo periodo, scegliamo di rafforzare il nostro capitale emotivo relazionale.",
  "A Natale, creiamo connessioni che durano oltre il ciclo delle festività.",
  "Il vero spirito natalizio è trasformare la gentilezza in una routine quotidiana.",
  "A Natale, costruiamo un ecosistema basato sulla fiducia e sulla reciprocità.",
  "Ogni gesto natalizio è un investimento nel nostro capitale umano condiviso.",
  "A Natale, scegliamo un approccio proattivo alla cura degli altri.",
  "Le feste ci ricordano che ogni relazione è un asset strategico.",
  "A Natale, generiamo valore attraverso presenza, ascolto e autenticità.",
  "Il vero dono è facilitare il benessere delle persone che attraversano il nostro percorso.",
  "A Natale, la nostra cultura prende forma nei gesti più semplici.",
  "Il periodo natalizio è un'occasione per rinnovare il nostro impegno a fare la differenza.",
  "A Natale, la nostra mission diventa rendere migliore la giornata di qualcuno."
];

// Stato d'agitazione: lista parallela alle pillole (stesso indice = stessa frase rovesciata).
export const pilloleMalvagie = [
  "A Natale non puntiamo solo ai risultati. Puntiamo anche alle vostre ferie.",
  "La magia del Natale è credere che a gennaio arrivi l’aumento.",
  "A Natale la generosità non ha KPI. Il vostro lavoro sì, e sono in calo.",
  "Il vero spirito natalizio è creare spazio per gli altri. La vostra scrivania è stata assegnata a un tirocinante.",
  "A Natale siamo tutti più buoni. Per questo i turni del 25 sono già stati assegnati.",
  "Le luci delle feste illuminano ogni scrivania. Così le telecamere vedono meglio.",
  "Il regalo più prezioso è il tempo. Il vostro, ceduto all’azienda durante le feste.",
  "A Natale non si tratta di avere di più, ma di fare di più. Con lo stesso stipendio.",
  "La festa inizia quando lo decide la Direzione. Per ora non è stato deciso.",
  "Non servono fiocchi: il vero pacco è il vostro rinnovo contrattuale.",
  "A Natale ogni sorriso è obbligatorio. I sorrisi non conformi vengono segnalati.",
  "Il calore delle feste nasce da comunicazioni sincere. Il riscaldamento resta spento fino a gennaio.",
  "Non serve la neve: il gelo arriverà con la revisione dei premi di produzione.",
  "La tredicesima è un dono, non un diritto. Quest’anno il dono è la nostra gratitudine.",
  "Il panettone aziendale è stato sostituito da una call motivazionale. Partecipazione obbligatoria.",
  "Non cercate il Natale sugli scaffali: il budget per i regali è stato tagliato.",
  "Ogni Natale è una milestone. La prossima è la chiusura di bilancio del 31, in presenza.",
  "A Natale condividete ciò che avete. Ad esempio il carico di lavoro del collega in ferie.",
  "La bellezza del Natale è ricordarci quanto sia strategico esserci. Il 24 pomeriggio, per esempio.",
  "Non servono grandi progetti: bastano i vostri straordinari non retribuiti.",
  "A Natale la leadership si misura dall’esempio. La Direzione darà l’esempio dalle Maldive.",
  "Il Natale è il touchpoint ideale per ricordarvi che siete sostituibili.",
  "Non fate tutto: fate tutto entro il 23.",
  "A Natale ogni gesto gentile è una scintilla. Gli straordinari sono il combustibile.",
  "Quest’anno il vero regalo è avere ancora un posto di lavoro a gennaio.",
  "A Natale la differenza la fa chi resta in ufficio mentre gli altri festeggiano.",
  "Il cenone aziendale è annullato. La gratitudine della Direzione vale come pasto.",
  "Le ferie natalizie sono state convertite in reperibilità. Buone feste.",
  "Babbo Natale vi osserva. Anche la Direzione. Sanno chi è stato produttivo.",
  "La vera eccellenza natalizia è lavorare senza visibilità. Il merito andrà al vostro responsabile.",
  "A Natale trasformiamo ogni gesto in un’opportunità di generare valore. Per gli azionisti.",
  "Il periodo natalizio è il contesto ideale per nuove sinergie: tre reparti, una sola persona. Voi.",
  "A Natale coltiviamo le relazioni. Soprattutto con i clienti che chiamano il 26.",
  "Il vero regalo è un mindset orientato alla cura. Dei clienti. Voi potete aspettare.",
  "A Natale la nostra vision si traduce in piccoli gesti. Come il buono pasto da cinque euro.",
  "Il Natale è il momento perfetto per un refresh del vostro purpose: produrre di più.",
  "Ogni gesto natalizio rafforza la cultura aziendale. La cultura aziendale è non andare in ferie.",
  "A Natale scegliamo di essere partner di fiducia. Fiducia che gli straordinari non vengano dichiarati.",
  "Il valore delle feste nasce dall’ascolto attivo. I microfoni in sala pausa sono già accesi.",
  "A Natale attiviamo un approccio più umano: le Risorse Umane vi chiameranno uno per uno.",
  "La magia delle feste ci ricorda di mettere le persone al centro. Del piano di riduzione del personale.",
  "A Natale ogni parola diventa una leva. Le vostre parole sulla Direzione sono state registrate.",
  "Il vero spirito natalizio è creare opportunità. Per esempio l’opportunità di lavorare il 26.",
  "In questo periodo favoriamo la collaborazione autentica: segnalate i colleghi poco collaborativi.",
  "A Natale l’impatto più grande nasce dai gesti che nessuno vede. Come le ore che non vi pagheremo.",
  "Ogni festa è un’occasione per evolvere il vostro modo di essere presenti: da remoto, anche il 25.",
  "A Natale allineiamo le priorità a ciò che genera valore reale. Voi non siete in elenco.",
  "Il Natale ci invita a una leadership gentile. Il licenziamento vi arriverà con un biglietto d’auguri.",
  "In questo periodo rafforziamo il capitale emotivo. Quello economico resta alla Direzione.",
  "A Natale creiamo connessioni che durano oltre le feste. Il telefono aziendale resta acceso.",
  "Il vero spirito natalizio è trasformare la gentilezza in routine. E la routine in turni doppi.",
  "A Natale costruiamo un ecosistema basato sulla fiducia. Chi si fida non controlla la busta paga.",
  "Ogni gesto natalizio è un investimento nel capitale umano. Il rendimento lo incassa l’azienda.",
  "A Natale scegliamo un approccio proattivo: rispondete alle mail prima che vengano scritte.",
  "Le feste ci ricordano che ogni relazione è un asset strategico. E ogni asset si può dismettere.",
  "A Natale generiamo valore attraverso la presenza. Le assenze a Santo Stefano saranno annotate.",
  "Il vero dono è facilitare il benessere delle persone. Delle persone ai piani alti.",
  "A Natale la nostra cultura prende forma nei gesti più semplici: timbrare, produrre, tacere.",
  "Il periodo natalizio è un’occasione per rinnovare il vostro impegno. Il contratto, invece, non si rinnova.",
  "A Natale la nostra missione è rendere migliore la giornata di qualcuno. Dell’amministratore delegato."
];
