// Pillole natalizie (8 dicembre - 6 gennaio).
export const pillole = [
  "A Natale, non puntiamo solo ai risultati: diventiamo il valore aggiunto nelle vite degli altri.",
  "La magia del Natale è credere che ogni piccolo gesto possa generare un impatto significativo.",
  "La generosità non ha KPI: praticatela ogni giorno come fosse parte della strategia.",
  "Il vero spirito natalizio è creare spazio per gli altri, proprio come facciamo per idee e opportunità.",
  "A Natale, la gentilezza è il nostro personal branding migliore.",
  "Non cercate luci esterne: siate il faro che guida stakeholder e persone vicine.",
  "Il regalo più prezioso è il tempo investito in relazioni che generano valore.",
  "A Natale, non si tratta di avere di più, ma di *essere più* per la comunità che costruiamo.",
  "La festa inizia quando attiviamo il nostro mindset aperto e collaborativo.",
  "Non servono fiocchi: l’autenticità è il packaging più potente.",
  "A Natale, ogni sorriso è una micro-azione che illumina il percorso condiviso.",
  "Il calore delle feste nasce da comunicazioni sincere e connessioni autentiche.",
  "Non serve la neve: basta la predisposizione ad accogliere con un mindset positivo.",
  "A Natale, la gratitudine è il collante che rafforza ogni partnership e relazione.",
  "Il vero spirito natalizio è fare il bene senza aspettare una call to action.",
  "Non cercate il Natale sugli scaffali: trovatelo nei valori che mettiamo in pratica.",
  "Ogni Natale è una milestone per ripartire con più consapevolezza e meno frenesia.",
  "A Natale, il valore non è ciò che riceviamo, ma ciò che scegliamo di condividere.",
  "La bellezza del Natale è ricordarci quanto sia strategico esserci, davvero.",
  "Non servono grandi progetti: basta presenza autentica per fare la differenza.",
  "A Natale, la leadership si misura nella capacità di ispirare attraverso l’esempio.",
  "Il Natale è il touchpoint ideale per riscoprire il valore della gentilezza.",
  "Non fate tutto: fate spazio a ciò che contribuisce davvero agli obiettivi comuni.",
  "A Natale, ogni gesto gentile è una scintilla che alimenta l’energy del team.",
  "Il vero dono è essere presenti, ascoltare attivamente e creare connessioni.",
  "A Natale, la differenza la fa chi sceglie di essere luce nel percorso formativo di qualcun altro.",
  "Non aspettate il cenone: celebrate ogni micro-successo e ogni gesto di cura.",
  "Il Natale è un prompt per rallentare, riflettere e riallinearsi con i nostri valori.",
  "A Natale, non siate spettatori: siate generatori di impatto positivo.",
  "La vera eccellenza natalizia è fare il bene senza bisogno di metriche o visibilità.",
  "A Natale, trasformiamo ogni gesto in un’opportunità di generare valore condiviso.",
  "Il periodo natalizio è il contesto ideale per abilitare nuove sinergie umane.",
  "A Natale, coltiviamo relazioni che supportano il nostro ecosistema di persone.",
  "Il vero regalo è investire in un mindset orientato alla cura e alla collaborazione.",
  "A Natale, la nostra vision si traduce in piccoli gesti che creano grande impatto.",
  "Il Natale è il momento perfetto per fare un refresh del nostro purpose personale.",
  "Ogni gesto natalizio è un touchpoint che rafforza la nostra cultura umana e professionale.",
  "A Natale, scegliamo di essere partner di fiducia per chi ci circonda.",
  "Il valore delle feste nasce da connessioni basate su empatia e ascolto attivo.",
  "A Natale, attiviamo un approccio più umano al nostro percorso di crescita.",
  "La magia delle feste è un reminder di quanto sia importante mettere le persone al centro.",
  "A Natale, ogni parola diventa una leva di ispirazione e benessere condiviso.",
  "Il vero spirito natalizio è creare opportunità, non aspettare che arrivino.",
  "In questo periodo, modelliamo un ambiente che favorisce la collaborazione autentica.",
  "A Natale, l’impatto più grande nasce dai gesti che nessuno vede.",
  "Ogni festa è un’occasione per evolvere il nostro modo di essere presenti.",
  "A Natale, allineiamo le nostre priorità a ciò che genera valore reale.",
  "Il Natale ci invita a praticare una leadership gentile e rigenerativa.",
  "In questo periodo, scegliamo di rafforzare il nostro capitale emotivo relazionale.",
  "A Natale, creiamo connessioni che durano oltre il ciclo delle festività.",
  "Il vero spirito natalizio è trasformare la gentilezza in una routine quotidiana.",
  "A Natale, costruiamo un ecosistema basato sulla fiducia e sulla reciprocità.",
  "Ogni gesto natalizio è un investimento nel nostro capitale umano condiviso.",
  "A Natale, scegliamo un approccio proattivo alla cura degli altri.",
  "Le feste ci ricordano che ogni relazione è un asset strategico.",
  "A Natale, generiamo valore attraverso presenza, ascolto e autenticità.",
  "Il vero dono è facilitare il benessere delle persone che attraversano il nostro percorso.",
  "A Natale, la nostra cultura prende forma nei gesti più semplici.",
  "Il periodo natalizio è un'occasione per rinnovare il nostro impegno a fare la differenza.",
  "A Natale, la nostra mission diventa rendere migliore la giornata di qualcuno."
];

// Stato d'agitazione: la versione malvagia, scelta con lo stesso numero del giorno.
export const pilloleMalvagie = [
  "A Natale siamo tutti più buoni. Per questo i turni del 25 sono già stati assegnati.",
  "La tredicesima è un dono, non un diritto. Quest’anno il dono è la nostra gratitudine.",
  "Il regalo più prezioso è il tempo. Il vostro, ceduto all’azienda durante le feste.",
  "Il panettone aziendale è stato sostituito da una call motivazionale. Partecipazione obbligatoria.",
  "A Natale la generosità non ha KPI. Il vostro lavoro sì, e sono in calo.",
  "Babbo Natale vi osserva. Anche la Direzione. Sanno chi è stato produttivo.",
  "Le ferie natalizie sono state convertite in reperibilità. Buone feste.",
  "A Natale condividete ciò che avete. Ad esempio il carico di lavoro del collega in ferie.",
  "Il cenone aziendale è annullato. La gratitudine della Direzione vale come pasto.",
  "Quest’anno il vero regalo è avere ancora un posto di lavoro a gennaio.",
  "La magia del Natale è credere che a gennaio arrivi l’aumento.",
  "Le luci delle feste illuminano ogni scrivania. Così le telecamere vedono meglio."
];
