export const pillole = [
  "Non aspettate il momento perfetto. Createne uno.",
  "Ogni sfida è un’opportunità mascherata da ostacolo.",
  "Non fate solo il vostro dovere. Fate la differenza.",
  "La passione è il motore. La costanza è la strada.",
  "Non temete di sbagliare. Temete di non provare.",
  "Siate curiosi. La curiosità è il primo passo verso il cambiamento.",
  "Il successo non è una destinazione. È un’attitudine.",
  "Non lavorate solo per un obiettivo. Lavorate per un significato.",
  "Ogni giorno è una scelta. Scegliete di essere eccellenti.",
  "Non aspettate che qualcuno vi motivi. Siate la vostra ispirazione.",
  "Non siate solo parte del cambiamento. Siate il motivo per cui accade.",
  "Il talento è un dono. La disciplina è una scelta.",
  "Non cercate la strada più facile. Cercate quella che vi migliora.",
  "Ogni errore è un maestro che parla a chi sa ascoltare.",
  "Non lavorate per il successo. Lavorate per il valore.",
  "La vera innovazione nasce dove finisce la comodità.",
  "Non siate reattivi. Siate proattivi.",
  "Il tempo è limitato. Usatelo per costruire, non per sopravvivere.",
  "Non aspettate di avere tutto. Iniziate con ciò che avete.",
  "La leadership non è un titolo. È un esempio.",
  "Non cercate di piacere a tutti. Cercate di essere autentici.",
  "Il futuro non si prevede. Si crea.",
  "Non temete la fatica. Temete la stagnazione.",
  "La crescita inizia dove finisce la zona di comfort.",
  "Non fate le cose perché vanno fatte. Fatele perché ci credete.",
  "Il successo è la somma di piccoli sforzi ripetuti ogni giorno.",
  "Non siate spettatori della vostra vita. Siate i protagonisti.",
  "La passione è contagiosa. Diffondetela.",
  "Non cercate scuse. Cercate soluzioni.",
  "Il mondo cambia quando cambiate il vostro modo di vederlo.",
  "Non accontentatevi di essere bravi. Puntate a essere unici.",
  "La vera forza è restare gentili in un mondo che non lo è sempre.",
  "Non cercate il perché del fallimento. Cercate il come della ripartenza.",
  "Il talento vi porta in alto. Il carattere vi mantiene lì.",
  "Non fate le cose per doverle fare. Fatele perché vi rappresentano.",
  "Ogni giorno è una nuova possibilità. Non sprecatela.",
  "Non temete di essere diversi. Temete di essere uguali a tutti.",
  "La vera competizione è con voi stessi. Ogni giorno, un passo in più.",
  "Non aspettate che qualcosa cambi. Siate voi il cambiamento.",
  "La conoscenza è potere. La saggezza è responsabilità.",
  "Non cercate di fare tutto. Cercate di fare bene ciò che conta.",
  "Il coraggio non è non avere paura. È agire nonostante la paura.",
  "Non siate solo efficienti. Siate ispiranti.",
  "La vera eccellenza è fare le cose semplici in modo straordinario.",
  "Non lavorate per un posto. Lavorate per una missione.",
  "Il successo è una conseguenza. La dedizione è la causa.",
  "Non cercate di essere perfetti. Cercate di essere migliori di ieri.",
  "La vera ricchezza è fare ciò che amate e sapere perché lo fate.",
  "Non temete il giudizio. Temete di non essere fedeli a voi stessi.",
  "La passione crea strade dove la logica vede muri.",
  "Non siate solo parte di un team. Siate la sua energia.",
  "Il valore di ciò che fate è nel perché lo fate.",
  "Non cercate di fare tutto da soli. Cercate di fare insieme ciò che conta.",
  "La vera integrità è fare la cosa giusta anche quando nessuno guarda.",
  "Non siate solo veloci. Siate consapevoli.",
  "Il lavoro non è solo produrre. È creare impatto.",
  "Non cercate di piacere a tutti. Cercate di essere utili a qualcuno.",
  "La vera innovazione è il coraggio di pensare diversamente.",
  "Non fate solo quello che vi viene chiesto. Fate quello che serve.",
  "La vostra voce ha valore. Usatela per costruire.",
  "Non aspettate l’ispirazione. Createla con le azioni.",
  "La vera competenza è sapere quando imparare di nuovo.",
  "Non fate solo domande. Siate la risposta che serve.",
  "Il successo non è una meta. È un modo di vivere.",
  "Non cercate di essere i migliori. Cercate di essere utili.",
  "La vera crescita è quando il comfort lascia spazio alla scoperta.",
  "Non temete di ricominciare. Ogni inizio è una nuova forza.",
  "Il lavoro è un luogo di valori. Non solo di compiti.",
  "Non cercate la perfezione. Cercate l’evoluzione.",
  "La vera motivazione nasce dal perché, non dal come.",
  "Non siate solo presenti. Siate coinvolti.",
  "Il tempo è un investimento. Usatelo per costruire futuro.",
  "Non fate le cose per abitudine. Fatele per convinzione.",
  "La vera eccellenza è fare il proprio meglio anche quando nessuno guarda.",
  "Non cercate di controllare tutto. Cercate di dare il meglio in ogni cosa.",
  "Il cambiamento non si aspetta. Si guida.",
  "Non siate solo esecutori. Siate ideatori.",
  "La vera leadership è servire, non comandare.",
  "Non temete di essere imperfetti. Temete di non essere reali.",
  "Il valore di una persona non sta in ciò che fa, ma in come lo fa.",
  "Non cercate di evitare i problemi. Cercate di risolverli con intelligenza.",
  "La vera influenza è l’esempio che date, non le parole che usate.",
  "Non siate solo strumenti. Siate visioni in azione.",
  "Il successo è un viaggio che inizia con la scelta di crederci.",
  "Non cercate di fare tutto. Cercate di fare ciò che conta.",
  "La vera motivazione è sapere per chi e perché lo fai.",
  "Non temete il cambiamento. Temete la resistenza a crescere.",
  "Il lavoro è un’opportunità per lasciare un segno.",
  "Non cercate di essere invisibili. Cercate di essere indimenticabili.",
  "La vera passione non si dichiara. Si dimostra.",
  "Non cercate di fare rumore. Cercate di lasciare un’eco.",
  "La vera professionalità è unire competenza e cuore.",
  "Non siate solo risultati. Siate relazioni.",
  "Il valore di un’azienda è nelle persone che la vivono.",
  "Non cercate di essere indispensabili. Cercate di essere indimenticabili.",
  "La vera cultura aziendale si costruisce con ogni gesto quotidiano.",
  "Non temete di cambiare rotta. Temete di non avere una direzione.",
  "Il lavoro è un’espressione di chi siete. Fatene un’opera.",
  "Non cercate di fare la differenza. Siate la differenza.",
  "Siate il meglio di qualunque cosa siate. Cercate ardentemente di scoprire a cosa siete chiamati, poi mettetevi a farlo appassionatamente."
];

export const pilloleNatalizie = [
  "A Natale, non cercate regali perfetti. Siate voi il dono che illumina gli altri.",
  "La magia del Natale è credere che ogni gesto gentile possa cambiare il mondo.",
  "Non aspettate il momento giusto per essere generosi. Ogni giorno è Natale per chi dona con il cuore.",
  "Il vero spirito natalizio è fare spazio agli altri, non solo sotto l’albero ma anche nella vita.",
  "A Natale, la gentilezza è la decorazione più bella che potete indossare.",
  "Non cercate luci fuori. Siate la luce che scalda chi vi sta vicino.",
  "Il regalo più prezioso è il tempo condiviso con chi conta davvero.",
  "A Natale, non si tratta di avere di più, ma di essere di più per gli altri.",
  "La vera festa è quando il cuore si apre, non solo la porta di casa.",
  "Non servono fiocchi per impacchettare l’amore. Basta un gesto sincero.",
  "A Natale, ogni sorriso è una stella che illumina il cammino di qualcuno.",
  "Il calore delle feste nasce da parole gentili e abbracci sinceri.",
  "Non aspettate la neve per sentire la magia. Basta un cuore che sa accogliere.",
  "A Natale, la gratitudine è il filo d’oro che lega ogni relazione.",
  "Il vero spirito natalizio è fare del bene senza aspettarsi nulla in cambio.",
  "Non cercate il Natale nei negozi. Cercatelo nei ricordi, nei gesti, nei legami.",
  "Ogni Natale è un’opportunità per ricominciare con più amore e meno fretta.",
  "A Natale, non si tratta di ciò che ricevi, ma di ciò che scegli di donare.",
  "La bellezza del Natale è che ci ricorda quanto sia importante esserci, davvero.",
  "Non servono grandi cose per fare Natale. Basta esserci con il cuore.",
  "A Natale, la vera leadership è servire con gioia e ispirare con l’esempio.",
  "Il Natale è il momento perfetto per riscoprire il valore della gentilezza.",
  "Non cercate di fare tutto. Cercate di fare spazio a ciò che conta davvero.",
  "A Natale, ogni gesto gentile è una scintilla che accende la speranza.",
  "Il vero dono è essere presenti, ascoltare, abbracciare, comprendere.",
  "A Natale, la differenza la fa chi sceglie di essere luce nel buio di qualcuno.",
  "Non aspettate il cenone per celebrare. Celebrate ogni piccolo gesto d’amore.",
  "Il Natale è un invito a rallentare, riflettere e riconnettersi con ciò che conta.",
  "A Natale, non siate solo spettatori. Siate protagonisti di gesti che scaldano il cuore.",
  "La vera eccellenza natalizia è fare il bene senza che nessuno lo veda."
];